global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['jobmanager:9250']
    
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['taskmanager:9250']
